name: repro_json_serializable_issue
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  built_collection: ^5.1.1
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.7
  lints: ^1.0.0
  json_serializable: ^6.1.4
